/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/restaurants' | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/restaurants' | '/restaurants/$id'
  id: '__root__' | '/' | '/restaurants' | '/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
